name: relase images
on:
  push:
    branches:
      - main
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{  github.token }}

      - name: Build and publish images
        run: just build-push-images
        env:
          docker_user: ${{ github.actor }}
          docker_password: ${{ github.token }}